---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Install Docker
      block:
        - name: Added universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Installing additional packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true
            cache_valid_time: 86400

        - name: Add Docker key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Install stabile repo
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker

        - name: Install Docker-ce
          apt:
            name: docker-ce
            update-cache: true

        - name: Check Docker install and reboot
          service:
            name: docker
            state: restarted
            enabled: true
      become: true

    - name: Install Docker-compose
      block:
        - name: Get last version Docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Install Docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true

    - name: Install finish
      block:
        - name: Add user in group Docker
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

        - name: Reboot
          reboot:
      become: true
